import {build} from "esbuild";
import {mkdir} from "node:fs/promises";
import {spawnSync} from "node:child_process";
await mkdir(".sites-runtime/tests",{recursive:true});
await build({entryPoints:["tests/inventory.test.ts"],outfile:".sites-runtime/tests/inventory.test.mjs",bundle:true,platform:"node",format:"esm",target:"node22"});
const result=spawnSync(process.execPath,["--test",".sites-runtime/tests/inventory.test.mjs"],{stdio:"inherit"});
await build({entryPoints:["tests/daily-inventory.test.ts"],outfile:".sites-runtime/tests/daily-inventory.test.mjs",bundle:true,platform:"node",format:"esm",target:"node22"});
const daily=spawnSync(process.execPath,["--test",".sites-runtime/tests/daily-inventory.test.mjs"],{stdio:"inherit"});
await build({entryPoints:["tests/inbound.test.ts"],outfile:".sites-runtime/tests/inbound.test.mjs",bundle:true,platform:"node",format:"esm",target:"node22"});
const inbound=spawnSync(process.execPath,["--test",".sites-runtime/tests/inbound.test.mjs"],{stdio:"inherit"});
const stream=spawnSync(process.execPath,["--test","tests/dingtalk-stream.test.mjs"],{stdio:"inherit"});
await build({entryPoints:["tests/dingtalk-groups.test.ts"],outfile:".sites-runtime/tests/dingtalk-groups.test.mjs",bundle:true,platform:"node",format:"esm",target:"node24"});
const groups=spawnSync(process.execPath,["--test",".sites-runtime/tests/dingtalk-groups.test.mjs"],{stdio:"inherit"});
process.exitCode=result.status || daily.status || inbound.status || stream.status || groups.status || 0;
