"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowDownToLine, ArrowDownUp, ArrowLeft, ArrowRight, BellRing, Box, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, Database, ExternalLink, LayoutGrid, LoaderCircle, PackageOpen, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, TrendingDown, Warehouse } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Pagination } from "@/components/ui/pagination";
import { SidebarProvider, SidebarMenuButton } from "@/components/ui/sidebar";
import type { ScopeInfo } from "@/lib/stock-scope";
import type { InventoryView, RunInfo } from "@/lib/inventory-types";
import type { AlertSettings } from "@/lib/alerts-store";

const quantity = (value: string) => { const [a,b] = value.split("."); return a.replace(/\B(?=(\d{3})+(?!\d))/g, ",") + (b ? "." + b : ""); };
const time = (value: string) => value.length === 10 ? value : new Date(value).toLocaleString("zh-CN", { timeZone: "Asia/Shanghai", hour12: false });
async function apiJson<T>(response:Response):Promise<T> {
  const data=await response.json() as {error?:string};
  if(!response.ok) throw new Error(data.error||"请求失败，请重试");
  return data as T;
}

function Sparkline({ values, large = false }: { values: (string | null)[]; large?: boolean }) {
  const w = large ? 500 : 120, h = large ? 110 : 32, points = values.map(v => v === null ? null : Number(v));
  const present = points.filter((n): n is number => n !== null);
  if (!present.length) return <span className="no-history">暂无记录</span>;
  const low = Math.min(...present), range = Math.max(...present) - low || 1;
  const xy = (n: number, i: number) => [8 + i / Math.max(1,points.length - 1) * (w - 16), h - 7 - (n - low) / range * (h - 14)];
  let path = "", connected = false;
  points.forEach((n,i) => { if (n === null) { connected = false; return; } const [x,y] = xy(n,i); path += `${connected ? "L" : "M"}${x},${y} `; connected = true; });
  return <svg className="sparkline" width={w} height={h} viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`${present.length} 天真实库存记录`}><path d={`M8,${h-7} H${w-8}`} stroke="#e4ebf2" strokeDasharray="3 3"/><path d={path} fill="none" stroke="#3b6de9" strokeWidth={large ? 2.5 : 1.7}/>{points.map((n,i) => n === null ? null : <circle key={i} cx={xy(n,i)[0]} cy={xy(n,i)[1]} r={present.length === 1 ? 3.5 : 2} fill="#3b6de9"/>)}</svg>;
}

export default function InventoryDashboard({ initial }: { initial: InventoryView }) {
  const [view,setView] = useState(initial), [section,setSection] = useState("inventory");
  const [search,setSearch] = useState(""), [query,setQuery] = useState(""), [filter,setFilter] = useState("all"), [days,setDays] = useState("14"), [page,setPage] = useState(1), [sort,setSort] = useState("code");
  const [source,setSource] = useState("auto"), [refresh,setRefresh] = useState(0), [loading,setLoading] = useState(false), [syncing,setSyncing] = useState(false), [exporting,setExporting] = useState(false);
  const [runs,setRuns] = useState<RunInfo[]>([]), [notice,setNotice] = useState(""), [error,setError] = useState("");
  const [help,setHelp] = useState(false), [selected,setSelected] = useState<InventoryView["rows"][number] | null>(null);
  const [alerts,setAlerts] = useState<AlertSettings>({ enabled:false, threshold:"0", lastSentAt:null, lastResult:null, robotConfigured:initial.robotConfigured });
  const [threshold,setThreshold] = useState("0"), [enabled,setEnabled] = useState(false), [saving,setSaving] = useState(false);
  const [scope,setScope] = useState<(ScopeInfo & {barcodes:string}) | null>(null), [scopeOpen,setScopeOpen] = useState(false), [scopeText,setScopeText] = useState(""), [scopeLabel,setScopeLabel] = useState("CK031 仓库条码清单"), [scopeSaving,setScopeSaving] = useState(false);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); },300); return () => clearTimeout(timer); },[search]);
  useEffect(() => {
    const controller = new AbortController();
    const params = new URLSearchParams({ q:query, filter, days, page:String(page), sort, source });
    fetch(`/api/inventory?${params}`,{ signal:controller.signal }).then(r=>apiJson<InventoryView>(r)).then(d=>{setView(d);setError("");}).catch(e => { if (e.name !== "AbortError") setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  },[query,filter,days,page,sort,source,refresh]);
  useEffect(() => { fetch("/api/alerts").then(r=>apiJson<AlertSettings>(r)).then(d=>{setAlerts(d);setThreshold(d.threshold);setEnabled(d.enabled);}).catch(e => setError(e.message)); },[refresh]);
  useEffect(() => { fetch("/api/scope").then(r=>apiJson<(ScopeInfo & {barcodes:string}) | null>(r)).then(d=>{setScope(d);if(d){setScopeText(d.barcodes);setScopeLabel(d.label);}}).catch(e=>setError(e.message)); },[refresh]);
  useEffect(() => {
    const modelContext = (document as Document & { modelContext?: { registerTool: (tool: unknown, options: {signal:AbortSignal}) => unknown } }).modelContext;
    if(!modelContext?.registerTool) return;
    const lifecycle = new AbortController();
    try {
      void Promise.resolve(modelContext.registerTool({
        name:"inspect_inventory", title:"查询库存", description:"读取当前仓库库存快照，按货品编码或名称和库存状态筛选；不采集、不发送消息。",
        inputSchema:{type:"object",properties:{query:{type:"string",maxLength:200},filter:{type:"string",enum:["all","positive","zero","negative"]}},additionalProperties:false},
        annotations:{readOnlyHint:true,untrustedContentHint:true},
        async execute(input:unknown) {
          if(!input || typeof input!=="object" || Array.isArray(input)) throw new Error("参数须为对象");
          const value=input as Record<string,unknown>;
          if(Object.keys(value).some(k=>!['query','filter'].includes(k)) || (value.query!==undefined && (typeof value.query!=="string" || value.query.length>200)) || (value.filter!==undefined && !["all","positive","zero","negative"].includes(String(value.filter)))) throw new Error("筛选参数无效");
          const data=await apiJson<InventoryView>(await fetch(`/api/inventory?${new URLSearchParams({q:String(value.query||""),filter:String(value.filter||"all")})}`));
          return { source:data.source,scope:data.snapshot?.scope,matchedGoods:data.totalRows,rows:data.rows.map(r=>({goodsNo:r.goodsNo,goodsName:r.goodsName,quantity:r.quantity,unit:r.unitName})) };
        }
      },{signal:lifecycle.signal})).catch(()=>{});
    } catch { /* Browser without WebMCP still has the complete visible interface. */ }
    return ()=>lifecycle.abort();
  },[]);
  useEffect(() => {
    if (section !== "runs" && !syncing) return;
    const load = () => fetch("/api/sync").then(r=>apiJson<{runs:RunInfo[]}>(r)).then(d=>setRuns(d.runs)).catch(e => setError(e.message));
    load(); const timer = syncing ? setInterval(load,2000) : null; return () => { if (timer) clearInterval(timer); };
  },[section,syncing,refresh]);
  const dates = useMemo(() => Array.from({ length:Number(days) },(_,i) => { const d = new Date((view.snapshot?.date || new Date().toISOString().slice(0,10)) + "T00:00:00Z"); d.setUTCDate(d.getUTCDate()-i); return d.toISOString().slice(0,10); }),[view.snapshot?.date,days]);
  const totalPages = Math.max(1,Math.ceil(view.totalRows/view.pageSize));
  async function sync() {
    if(!scope) {setScopeOpen(true);return;}
    setSyncing(true); setError(""); setNotice("正在逐页采集，完成后会更新库存。");
    try { const r = await fetch("/api/sync",{ method:"POST" }), d = await apiJson<{recordCount:number;goodsCount:number}>(r); setSource("auto"); setPage(1); setRefresh(v=>v+1); setNotice(`已采集 ${d.recordCount.toLocaleString()} 条记录，汇总 ${d.goodsCount.toLocaleString()} 个货品。`); }
    catch(e) { setNotice(""); setError(e instanceof Error ? e.message : "采集失败"); } finally { setSyncing(false); }
  }
  async function exportExcel() {
    setExporting(true); setError("");
    try { const r = await fetch(`/api/export?source=${view.source}`); if (!r.ok) await apiJson(r); const url = URL.createObjectURL(await r.blob()), a = document.createElement("a"); a.href=url; a.download=`CK031_${view.source === "sample" ? "测试样本" : "库存汇总"}_${view.snapshot?.date}.xlsx`; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); setNotice("Excel 已导出；未接入的在途数量保留为空。"); }
    catch(e) { setError(e instanceof Error ? e.message : "导出失败"); } finally { setExporting(false); }
  }
  async function saveAlerts() {
    setSaving(true); setError("");
    try { const r = await fetch("/api/alerts",{ method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled,threshold}) }), d = await apiJson<AlertSettings>(r); setAlerts(d); setNotice(enabled ? "已开启预警：下一次完整采集后检查阈值并发送。" : "已关闭预警。"); }
    catch(e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setSaving(false); }
  }
  async function saveStockScope() {
    setScopeSaving(true);setError("");
    try { await apiJson(await fetch("/api/scope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcodes:scopeText,label:scopeLabel})}));setScopeOpen(false);setRefresh(v=>v+1);setNotice("采集范围已保存；请点击采集库存。预警已关闭，核对新范围后可重新开启。"); }
    catch(e) {setError(e instanceof Error?e.message:"保存范围失败");} finally {setScopeSaving(false);}
  }
  return <SidebarProvider className="inventory-shell">
    <aside className="sidebar"><Link className="brand" href="/"><span className="brand-icon"><Box size={25}/></span><span>仓库数据<span className="brand-sub">INVENTORY INSIGHTS</span></span></Link><div className="sidebar-label">数据中心</div><nav aria-label="功能导航"><SidebarMenuButton className={`nav-item ${section === "inventory" ? "active" : ""}`} onClick={()=>setSection("inventory")}><LayoutGrid size={19}/>库存分析<span className="nav-dot"/></SidebarMenuButton><SidebarMenuButton className={`nav-item ${section === "runs" ? "active" : ""}`} onClick={()=>setSection("runs")}><Clock3 size={19}/>采集记录</SidebarMenuButton></nav><div className="sidebar-label second">配置</div><SidebarMenuButton className={`nav-item ${section === "alerts" ? "active" : ""}`} onClick={()=>setSection("alerts")}><BellRing size={19}/>钉钉预警<span className="nav-state">{alerts.enabled ? "已启用" : "未开启"}</span></SidebarMenuButton><SidebarMenuButton className="nav-item" onClick={()=>setHelp(true)}><CircleHelp size={19}/>数据口径</SidebarMenuButton><div className="sidebar-bottom"><span className="source-icon"><Database size={18}/></span><div>吉客云开放平台<small>{view.configured ? "应用凭证已配置" : "等待配置应用凭证"}</small></div><span className={`status-dot ${view.configured ? "online" : ""}`}/></div></aside>
    <main className="workspace"><header className="topbar"><div className="breadcrumb">数据中心<ChevronRight size={15}/><strong>{section === "inventory" ? "库存分析" : section === "runs" ? "采集记录" : "钉钉预警"}</strong></div><div className="top-right"><span className="private-label"><ShieldCheck size={15}/>私有数据</span><span className="avatar">仓</span></div></header><div className="page-content">
      <div className="page-heading"><div><div className="eyebrow"><span/>CK031 · 泰国仓</div><h1>{section === "inventory" ? "仓库库存分析" : section === "runs" ? "数据采集记录" : "钉钉库存预警"}</h1><p>{view.warehouseName}<span className="heading-separator">/</span>{section === "inventory" ? "从可订购量了解当前库存" : section === "runs" ? "每一次采集都有据可查" : "将低库存货品汇总发送到群"}</p></div><div className="heading-actions"><Button variant="outline" className="outline-action scope-action" onClick={()=>setScopeOpen(true)}><Settings2/>采集范围</Button><Button variant="outline" className="outline-action" onClick={exportExcel} disabled={exporting||syncing}>{exporting ? <LoaderCircle className="spin"/> : <ArrowDownToLine/>}{view.source === "sample" ? "导出样本" : "导出 Excel"}</Button><Button className="primary-action" onClick={sync} disabled={syncing}>{syncing ? <LoaderCircle className="spin"/> : <RefreshCw/>}{syncing ? "采集中…" : "采集库存"}</Button></div></div>
      {error && <div className="message error" role="alert">{error}<button onClick={()=>setError("")} aria-label="关闭错误">×</button></div>}{notice && <div className="message success" role="status"><CheckCircle2 size={17}/>{notice}<button onClick={()=>setNotice("")} aria-label="关闭提示">×</button></div>}
      {section === "inventory" && <><div className="metrics-grid"><div className="metric"><span>汇总货品数<PackageOpen size={18}/></span><strong>{view.goodsCount.toLocaleString()}<small>个</small></strong><p>{view.source === "sample" ? "原始样本 12 条，非全仓数据" : `${view.snapshot?.recordCount.toLocaleString()} 条规格库存记录`}</p></div><div className="metric"><span>有效库存合计<Warehouse size={18}/></span><strong>{Object.keys(view.totalsByUnit).length === 1 ? quantity(Object.values(view.totalsByUnit)[0]) : "按单位"}<small>{Object.keys(view.totalsByUnit).length === 1 ? Object.keys(view.totalsByUnit)[0] : "汇总"}</small></strong><p>{Object.keys(view.totalsByUnit).length > 1 ? Object.entries(view.totalsByUnit).map(([u,q])=>`${q} ${u}`).join(" · ") : "口径：可订购量"}</p></div><div className="metric"><span>零库存货品<TrendingDown size={18}/></span><strong className="amber-value">{view.zeroCount.toLocaleString()}<small>个</small></strong><p>{view.negativeCount ? `另有 ${view.negativeCount} 个负库存货品` : "当前快照中可订购量等于 0"}</p></div><div className="metric"><span>已记录天数<Clock3 size={18}/></span><strong>{view.snapshots.length}<small>天</small></strong><p>{view.snapshots.length < 2 ? "首次记录，趋势等待后续采集" : "同一天采用最后一次完整快照"}</p></div></div>
      <section className="data-panel"><div className="panel-heading"><div className="panel-title"><h2>货品库存明细</h2><span className={`badge ${view.source === "sample" ? "sample" : "live"}`}>{view.source === "sample" ? "历史测试样本" : "条码范围采集"}</span></div><div className="update-label"><span className="status-dot online"/>{view.source === "sample" ? "样本日期" : "最后更新"} {view.snapshot ? time(view.snapshot.capturedAt) : "尚未采集"}<button onClick={()=>setRefresh(v=>v+1)} aria-label="刷新库存显示"><RefreshCw size={15}/></button></div></div>
      <div className="toolbar"><div className="search-box"><Search size={18}/><Input aria-label="搜索货品编码或名称" placeholder="搜索货品编码 / 名称" value={search} onChange={e=>setSearch(e.target.value)}/>{search && <button aria-label="清空搜索" onClick={()=>setSearch("")}>×</button>}</div><Select value={filter} onValueChange={v=>{setFilter(v);setPage(1);}}><SelectTrigger aria-label="库存状态" className="filter-select"><SlidersHorizontal size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部库存</SelectItem><SelectItem value="positive">有库存</SelectItem><SelectItem value="zero">零库存</SelectItem><SelectItem value="negative">负库存</SelectItem></SelectContent></Select><Select value={days} onValueChange={setDays}><SelectTrigger aria-label="展示天数" className="days-select"><Clock3 size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="7">近 7 天</SelectItem><SelectItem value="14">近 14 天</SelectItem><SelectItem value="30">近 30 天</SelectItem></SelectContent></Select><div className="toolbar-spacer"/><span className="table-hint">每日库存快照</span><button className="icon-button" onClick={()=>setHelp(true)} aria-label="查看库存口径"><CircleHelp size={17}/></button></div>
      <div className="scope-summary"><span>采集范围：{view.snapshot?.scope ? `${view.snapshot.scope.label} · ${view.snapshot.scope.count} 个条码` : scope ? `${scope.label} · ${scope.count} 个条码（尚未采集）` : "待设置完整条码清单"}</span><button onClick={()=>setScopeOpen(true)}>管理范围</button></div>{view.source === "sample" && <div className="sample-note"><Database size={15}/><span>当前为 12 条历史样本（测试应用 22914895）。配置应用 92058521 后，设置完整条码范围后，点击“采集库存”。</span></div>}
      <div className={`table-scroll ${loading ? "loading-table" : ""}`}><Table className="stock-table"><TableHeader><TableRow><TableHead className="sticky-number">序号</TableHead><TableHead className="sticky-goods">货品编码 / 名称</TableHead><TableHead className="trend-column">库存趋势<span>有记录的日期</span></TableHead><TableHead className="quantity-column"><button onClick={()=>{setSort(s=>s === "quantity" ? "code" : "quantity");setPage(1);}}>当前库存<ArrowDownUp size={13}/></button></TableHead><TableHead className="unit-column">单位</TableHead>{dates.map((d,i)=><TableHead key={d} className={`date-column ${i === 0 ? "latest" : ""}`}>{d.slice(5)}<span>{i === 0 ? "最新快照" : view.snapshots.some(s=>s.date === d) ? "已采集" : "未采集"}</span></TableHead>)}</TableRow></TableHeader><TableBody>{view.rows.map((row,i)=><TableRow key={row.goodsNo} onClick={()=>setSelected(row)} tabIndex={0} onKeyDown={e=>{if(e.key === "Enter")setSelected(row);}} aria-label={`查看 ${row.goodsNo} 库存详情`}><TableCell className="sticky-number">{(page-1)*view.pageSize+i+1}</TableCell><TableCell className="sticky-goods"><div className="goods-cell"><span className="product-symbol"><Box size={18}/></span><div><strong>{row.goodsNo}</strong><p title={row.goodsName}>{row.goodsName}</p></div></div></TableCell><TableCell><Sparkline values={[...dates].reverse().map(d=>row.history[d]??null)}/></TableCell><TableCell className={`quantity-cell ${row.quantity === "0" ? "zero-value" : row.quantity.startsWith("-") ? "negative-value" : ""}`}>{quantity(row.quantity)}</TableCell><TableCell className="unit-cell">{row.unitName}</TableCell>{dates.map((d,j)=><TableCell key={d} className={`daily-cell ${j === 0 ? "latest" : ""}`}>{row.history[d] == null ? <span className="missing">—</span> : quantity(row.history[d]!)}</TableCell>)}</TableRow>)}{!view.rows.length && <TableRow><TableCell colSpan={dates.length+5} className="empty-state"><Search size={30}/><strong>没有匹配的货品</strong><p>调整货品搜索或库存筛选后再试。</p><Button variant="outline" onClick={()=>{setSearch("");setFilter("all");setPage(1);}}>重置筛选</Button></TableCell></TableRow>}</TableBody></Table></div><div className="table-footer"><span>共 <strong>{view.totalRows.toLocaleString()}</strong> 个货品<span className="footer-divider">|</span>每页 {view.pageSize} 条</span><Pagination className="pagination" aria-label="库存分页"><Button variant="outline" size="icon" aria-label="上一页" disabled={page <= 1||loading} onClick={()=>setPage(p=>p-1)}><ArrowLeft size={15}/></Button><span><strong>{page}</strong> / {totalPages}</span><Button variant="outline" size="icon" aria-label="下一页" disabled={page >= totalPages||loading} onClick={()=>setPage(p=>p+1)}><ArrowRight size={15}/></Button></Pagination></div></section><p className="under-table"><span><Check size={14}/>库存快照来自吉客云分仓库存接口</span><span>在途数量将在入库申请接口接入后显示</span></p></>}
      {section === "runs" && <section className="data-panel history-panel"><div className="panel-heading"><div className="panel-title"><h2>最近 20 次采集</h2><span className="badge neutral">完整记录</span></div><button className="icon-button" onClick={()=>setRefresh(v=>v+1)} aria-label="刷新采集记录"><RefreshCw size={17}/></button></div><div className="history-scroll"><Table className="history-table"><TableHeader><TableRow><TableHead>开始时间</TableHead><TableHead>状态</TableHead><TableHead>请求页数</TableHead><TableHead>规格记录</TableHead><TableHead>汇总货品</TableHead><TableHead>说明</TableHead></TableRow></TableHeader><TableBody>{runs.map(r=><TableRow key={r.id}><TableCell>{time(r.startedAt)}</TableCell><TableCell><span className={`badge ${r.status === "complete" ? "live" : r.status === "failed" ? "failed" : "sample"}`}>{r.status === "complete" ? "成功" : r.status === "failed" ? "失败" : "采集中"}</span></TableCell><TableCell>{r.pageCount}</TableCell><TableCell>{r.recordCount.toLocaleString()}</TableCell><TableCell>{r.goodsCount.toLocaleString()}</TableCell><TableCell>{r.message||"逐页采集中…"}</TableCell></TableRow>)}</TableBody></Table>{!runs.length && <div className="records-empty"><Database size={36}/><h3>还没有正式采集记录</h3><p>配置吉客云应用凭证后，点击“采集库存”。测试样本不计入正式记录。</p></div>}</div><div className="explanation"><ShieldCheck size={19}/><div><strong>采集成功后才更新库存</strong><p>分页失败、重复页或货品字段冲突会终止采集，保留上一次完整数据。</p></div></div></section>}
      {section === "alerts" && <div className="alerts-layout"><section className="data-panel alerts-card"><div className="panel-heading"><div className="panel-title"><BellRing size={20}/><h2>群库存预警</h2></div><span className={`badge ${alerts.enabled ? "live" : "neutral"}`}>{alerts.enabled ? "已开启" : "已关闭"}</span></div><div className="alerts-body"><div className="toggle-row"><div><strong>采集完成后发送预警</strong><p>所选条码范围完整采集后发送；测试样本不发消息。</p></div><Switch checked={enabled} onCheckedChange={setEnabled} aria-label="开启库存预警"/></div><label className="threshold-field">低库存阈值<div><Input value={threshold} onChange={e=>setThreshold(e.target.value)} inputMode="decimal" aria-label="低库存阈值"/><span>可订购量 ≤ 此值时提醒</span></div></label><div className="config-state"><span className={`status-dot ${alerts.robotConfigured ? "online" : ""}`}/>{alerts.robotConfigured ? "机器人凭证与目标群已配置" : "等待配置机器人凭证与目标群"}</div><div className="alert-rules"><CheckCircle2 size={17}/><p>每次汇总发送最多 20 个货品明细，并提示其余数量。库存与阈值没有变化时，不重复发送同一条预警。</p></div><Button className="primary-action" onClick={saveAlerts} disabled={saving}>{saving ? <LoaderCircle className="spin"/> : <Check size={17}/>}保存预警设置</Button><p className="last-alert">最近发送：{alerts.lastSentAt ? time(alerts.lastSentAt) : "尚未发送"}<br/>{alerts.lastResult||"默认关闭，配置完成后由你开启。"}</p></div></section><section className="robot-guide"><span className="robot-guide-icon"><Settings2 size={24}/></span><h2>只接机器人，配置更简洁</h2><p>建立企业内部应用，启用“机器人与消息推送”并发布，再将机器人加入目标企业内部群。</p><ol><li>获取应用 Client ID / Client Secret</li><li>启用企业内机器人发送消息权限</li><li>填写 Robot Code 与目标群 ID</li><li>保存配置后，在此页面开启预警</li></ol><a href="https://open-dingtalk.github.io/developerpedia/docs/learn/bot/appbot/overview/" target="_blank" rel="noreferrer">钉钉官方配置说明<ExternalLink size={14}/></a><p className="guide-footnote">无需工作台页面。应用密钥仅在服务端保存。</p></section></div>}
    </div></main>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogHeader><DialogTitle>库存数据口径</DialogTitle><DialogDescription>第一期：分仓库存采集、汇总与预警</DialogDescription></DialogHeader><div className="help-content"><p><strong>现有库存</strong>取 <code>orderAbleQuantity</code>，按货品编码汇总同单位规格，负数保留。</p><p><strong>日期列与趋势</strong>来自每日真实采集快照。同日使用最后一次完整结果；缺失日期显示“—”，不填 0。</p><p><strong>在途、销量与建议补货</strong>本期尚未接入，在 Excel 中保持为空。库存变化不视为销量。</p><p><strong>测试样本</strong>为 12 条用户提供的历史记录，来自测试应用 22914895，不能代表全仓数量。</p><p><strong>Excel</strong>保留模板 A–H 业务列，填写物料编码、名称、现有库存，追加 I 列单位；“采集说明”页记录来源和范围。</p></div></DialogContent></Dialog>
    <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{selected?.goodsNo}</DialogTitle><DialogDescription>{selected?.goodsName}</DialogDescription></DialogHeader>{selected && <div className="detail-content"><div className="detail-current"><span>当前可订购量</span><strong>{quantity(selected.quantity)}<small>{selected.unitName}</small></strong><span>{selected.skuCount} 个规格汇总</span></div><h3>近 {days} 天库存记录</h3><Sparkline large values={[...dates].reverse().map(d=>selected.history[d]??null)}/><div className="detail-dates">{dates.filter(d=>selected.history[d]!=null).map(d=><div key={d}><span>{d}</span><strong>{quantity(selected.history[d]!)}</strong></div>)}</div><p>未采集日期保留为空，趋势不推算销量。</p></div>}</DialogContent></Dialog>
    <Dialog open={scopeOpen} onOpenChange={setScopeOpen}><DialogContent className="scope-dialog"><DialogHeader><DialogTitle>设置采集范围</DialogTitle><DialogDescription>粘贴该仓库的完整规格条码列。每批查询 500 个条码，每页读取 200 条记录。</DialogDescription></DialogHeader><label>范围名称<Input aria-label="范围名称" value={scopeLabel} onChange={e=>setScopeLabel(e.target.value)} maxLength={80}/></label><label>规格条码清单<Textarea aria-label="规格条码清单" placeholder="每行一个条码，可直接从 Excel 复制条码列" value={scopeText} onChange={e=>setScopeText(e.target.value)} className="scope-text"/></label><p className="scope-tip">条码取 <code>skuBarcode</code>。货品编码与条码相同时可使用编码。去除重复项后查询；未返回的条码会报告缺失，保留上次成功结果。清单完整性决定是否覆盖全仓。</p><Button onClick={saveStockScope} disabled={scopeSaving}>{scopeSaving?<LoaderCircle className="spin"/>:<Check/>}保存采集范围</Button></DialogContent></Dialog>
  </SidebarProvider>;
}

